# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spark < Formula
  desc "A simple cli to input and store your ideas directly with git and without a text editor"
  homepage ""
  version "1.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Chevalmuscle/spark/releases/download/v1.1.2/spark_1.1.2_Darwin_arm64.tar.gz"
      sha256 "0302e3a3173763fde4667f0b39bc27af43b42b2614ba36fb515d09f01f65c9d1"

      def install
        bin.install "spark"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Chevalmuscle/spark/releases/download/v1.1.2/spark_1.1.2_Darwin_x86_64.tar.gz"
      sha256 "e531831bb9aac21ad39ad2a620fa55cc6950f8422d0c51d9c7a3142773dfaf5c"

      def install
        bin.install "spark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chevalmuscle/spark/releases/download/v1.1.2/spark_1.1.2_Linux_arm64.tar.gz"
      sha256 "631432f95962398333aad3913e357c3f390d48ede8e96bb0079190eb7dbdfe08"

      def install
        bin.install "spark"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Chevalmuscle/spark/releases/download/v1.1.2/spark_1.1.2_Linux_x86_64.tar.gz"
      sha256 "41aab13e62efae54cef40e86585d6df45929f7108a39a369a7d6308e3ad5dba9"

      def install
        bin.install "spark"
      end
    end
  end

  head do
    url "https://github.com/chevalmuscke/spark.git"
    depends_on "go"
  end
end
