# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spark < Formula
  desc "A simple cli to input and store your ideas directly with git and without a text editor"
  homepage ""
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Chevalmuscle/spark/releases/download/v1.0.2/spark_1.0.2_Darwin_arm64.tar.gz"
      sha256 "df0cedd06c085f73db623878254ea1e4a82c6951194fc133977714e23cb47e80"

      def install
        bin.install "spark"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Chevalmuscle/spark/releases/download/v1.0.2/spark_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "74ea119d45a668aa28fbcdeab30b7e2ff4c9ff2da289d3e71471e0fd77fe55f0"

      def install
        bin.install "spark"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Chevalmuscle/spark/releases/download/v1.0.2/spark_1.0.2_Linux_arm64.tar.gz"
      sha256 "9c2e093a893773cad7da7b7c15a78c343d18388ea178600f91416c9950705d5e"

      def install
        bin.install "spark"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Chevalmuscle/spark/releases/download/v1.0.2/spark_1.0.2_Linux_x86_64.tar.gz"
      sha256 "605f3de7662033726f7339793988e0da66f79fdbc1fcf2553553157b31041319"

      def install
        bin.install "spark"
      end
    end
  end

  head do
    url "https://github.com/chevalmuscke/spark.git"
    depends_on "go"
  end
end
